---
name: Unpoller
version: 0.1.3.5
slug: unpoller
description: The open platform for beautiful analytics and monitoring
url: https://github.com/hassio-addons/addon-grafana
startup: application
boot: auto
hassio_role: default
apparmor: false
ingress: true
arch:
  - i386
  - aarch64
  - amd64
map:
  - config
  - ssl
  - addons
options:
  prometheus_disable: true
  influxdb_db: unifi
  influxdb_user: unifipoller
  influxdb_pass: unifipoller
  influxdb_url: http://192.168.1.20:8086
  unifi_default_user: kevin
  unifi_default_pass: Na1rdA!5652
  unifi_default_url: https://192.168.1.1
  poller_debug: false
  poller_quiet: true
  unifi_default_save_dpi: true
  ssl: true
  certfile: fullchain.pem
  keyfile: privkey.pem
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  prometheus_disable: bool
  influxdb_db: str
  influxdb_user: str
  influxdb_pass: str
  influxdb_url: str
  unifi_default_user: str
  unifi_default_pass: str
  unifi_default_url: str
  poller_debug: bool
  poller_quiet: bool
  unifi_default_save_dpi: bool
  ssl: bool
  certfile: str
  keyfile: str